apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: wait-microservices
spec:
  inputs:
    params:
      - name: namespace
        description:  the namespace where the services are running.
      - name: serivceName
        description: the name of the serivce
    resources:
      - name: level3-project
        type: git
  steps:
    - name: wait-for-other-pods
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "wait"
        - "--namespace"
        - "$(inputs.params.namespace)"
        - "--for=condition=ready"
        - "pods"
        - "-l"
        - "name=$(inputs.params.serivceName)"
        - "--timeout=900s"
