apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run-test
spec:
  inputs:
    resources:
      - name: level3-project
        type: git
  steps:
    - name: e2e-js-test
      image: "ozb96/e2e-test"
      command: ["/bin/sh"]
      args:
        - "-c"
        - "/app/runner.sh"
