apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-using-kubectl-test
spec:
  inputs:
    resources:
      - name: level3-project
        type: git
    params:
      - name: pathToYamlFile
        description: The path to the yaml file to deploy within the git source
      - name: namespace
        description: The namespace To use
  steps:
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "/workspace/level3-project/$(inputs.params.pathToYamlFile)"
        - "-n"
        - "$(inputs.params.namespace)"
