apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-using-kubectl-with-db
spec:
  inputs:
    resources:
      - name: level3-project
        type: git
    params:
      - name: pathToYamlFile
        description: The path to the yaml file to deploy within the git source
      - name: pathToServiceFile
        description: The yaml service file
      - name: namespace
        description: The namespace To use
      - name: pathToDBYamlFile
        description: the yaml file for the database service
      - name: pathToDBServiceFile
        description:  the yaml file for the service of the db
  steps:
    - name: run-kubectl-for-db
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "/workspace/level3-project/$(inputs.params.pathToDBYamlFile)"
        - "-f"
        - "/workspace/level3-project/$(inputs.params.pathToDBServiceFile)"
        - "-n"
        - "$(inputs.params.namespace)"
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "/workspace/level3-project/$(inputs.params.pathToYamlFile)"
        - "-f"
        - "/workspace/level3-project/$(inputs.params.pathToServiceFile)"
        - "-n"
        - "$(inputs.params.namespace)"

