apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: front-end-
spec:
  serviceAccountName: omar-docker-hub
  params:
  - name: IMAGE
    value: "ozb96/front-end"
  - name: pathToYamlFile
    value: "./front-end/front-end-dep.yaml"
  - name: pathToServiceFile
    value: "./front-end/front-end-svc.yaml"
  - name: namespace
    value: "test"
  - name: CONTEXT
    value: "/workspace/level3-project/front-end"
  - name: DOCKERFILE
    value: "/workspace/level3-project/front-end/Dockerfile"
  - name: pathToIngressFile
    value: "./front-end/front-end-ingress.yaml"
  - name: IMAGETEST
    value: "ozb96/e2e-test"
  - name: CONTEXTTEST
    value: "/workspace/level3-project/e2e-js-test"
  - name: DOCKERFILETEST
    value: "/workspace/level3-project/e2e-js-test/Dockerfile" 
  - name: namespaceProd
    value: "production"
  pipelineRef:
    name: build-deploy-run-ingress
  resources:
  - name: level3-project
    resourceRef:
      name: level3
