apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: queue-master-
spec:
  serviceAccountName: omar-docker-hub
  params:
  - name: IMAGE
    value: "ozb96/queue-master"
  - name: pathToYamlFile
    value: "./queue-master/queue-master-dep.yaml"
  - name: pathToServiceFile
    value: "./queue-master/queue-master-svc.yaml"
  - name: namespace
    value: "test"
  - name: CONTEXT
    value: "/workspace/level3-project/queue-master"
  - name: DOCKERFILE
    value: "/workspace/level3-project/queue-master/Dockerfile"
  - name: IMAGETEST
    value: "ozb96/e2e-test"
  - name: CONTEXTTEST
    value: "/workspace/level3-project/e2e-js-test"
  - name: DOCKERFILETEST
    value: "/workspace/level3-project/e2e-js-test/Dockerfile"
  - name: namespaceProd
    value: "production"

  pipelineRef:
    name: build-deploy-run
  resources:
  - name: level3-project
    resourceRef:
      name: level3
