apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: carts-
spec:
  serviceAccountName: omar-docker-hub
  params:
  - name: IMAGE
    value: "ozb96/carts"
  - name: serviceName
    value: "carts"
  - name: serviceDBName
    value: "carts-db"
  - name: pathToYamlFile
    value: "./YAML/carts-dep.yaml"
  - name: pathToServiceFile
    value: "./YAML/carts-svc.yaml"
  - name: namespace
    value: "test"
  - name: CONTEXT
    value: "/workspace/level3-project/carts"
  - name: DOCKERFILE
    value: "/workspace/level3-project/carts/Dockerfile"
  - name: DBIMAGE
    value: "mongo"
  - name: pathToDBYamlFile
    value: "./YAML/carts-db-dep.yaml"
  - name: pathToDBServiceFile
    value: "./YAML/carts-db-svc.yaml"
  - name: yamlfolders
    value:  "./YAML/"
  - name: namespaceProd
    value: "production"

  pipelineRef:
    name: build-deploy-run-db-without-data
  resources:
  - name: level3-project
    resourceRef:
      name: level3
