apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: shipping-
spec:
  serviceAccountName: omar-docker-hub
  params:
  - name: IMAGE
    value: "ozb96/shipping"
  - name: serivceName
    value: "shipping"
  - name: pathToYamlFile
    value: "./YAML/shipping-dep.yaml"
  - name: pathToServiceFile
    value: "./YAML/shipping-svc.yaml"
  - name: namespace
    value: "test"
  - name: CONTEXT
    value: "/workspace/level3-project/shipping"
  - name: DOCKERFILE
    value: "/workspace/level3-project/shipping/Dockerfile"
  - name: namespaceProd
    value: "production"

  pipelineRef:
    name: build-deploy-run
  resources:
  - name: level3-project
    resourceRef:
      name: level3
