apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: user-
spec:
  serviceAccountName: omar-docker-hub
  params:
  - name: IMAGE
    value: "ozb96/user"
  - name: serivceName
    value: "user"
  - name: serviceDBName
    value: "user-db"
  - name: pathToYamlFile
    value: "./YAML/user-dep.yaml"
  - name: pathToServiceFile
    value: "./YAML/user-svc.yaml"
  - name: namespace
    value: "test"
  - name: CONTEXT
    value: "/workspace/level3-project/user"
  - name: DOCKERFILE
    value: "/workspace/level3-project/user/Dockerfile"
  - name: DBIMAGE
    value: "ozb96/user-db"
  - name: pathToDBYamlFile
    value: "./YAML/user-db-dep.yaml"
  - name: pathToDBServiceFile
    value: "./YAML/user-db-svc.yaml"
  - name: DBCONTEXT
    value: "/workspace/level3-project/user/docker/user-db"
  - name: DBDOCKERFILE
    value: "/workspace/level3-project/user/docker/user-db/Dockerfile"
  - name: namespaceProd
    value: "production"

  pipelineRef:
    name: build-deploy-run-db
  resources:
  - name: level3-project
    resourceRef:
      name: level3
