apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: payment-
spec:
  serviceAccountName: omar-docker-hub
  params:
  - name: IMAGE
    value: "ozb96/payment"
  - name: serivceName
    value: "payment"
  - name: pathToYamlFile
    value: "./YAML/payment-dep.yaml"
  - name: pathToServiceFile
    value: "./YAML/payment-svc.yaml"
  - name: namespace
    value: "test"
  - name: CONTEXT
    value: "/workspace/level3-project/payment"
  - name: DOCKERFILE
    value: "/workspace/level3-project/payment/Dockerfile"
  - name: yamlfolders
    value:  "./YAML/"
  - name: namespaceProd
    value: "production"

  pipelineRef:
    name: build-deploy-run
  resources:
  - name: level3-project
    resourceRef:
      name: level3
