apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: orders-
spec:
  serviceAccountName: omar-docker-hub
  params:
  - name: IMAGE
    value: "ozb96/orders"
  - name: serivceName
    value: "orders"
  - name: serviceDBName
    value: "orders-db"
  - name: pathToYamlFile
    value: "./YAML/orders-dep.yaml"
  - name: pathToServiceFile
    value: "./YAML/orders-svc.yaml"
  - name: namespace
    value: "test"
  - name: CONTEXT
    value: "/workspace/level3-project/orders"
  - name: DOCKERFILE
    value: "/workspace/level3-project/orders/Dockerfile"
  - name: DBIMAGE
    value: "mongo:3.4"
  - name: pathToDBYamlFile
    value: "./YAML/orders-db-dep.yaml"
  - name: pathToDBServiceFile
    value: "./YAML/orders-db-svc.yaml"
  - name: namespaceProd
    value: "production"

  pipelineRef:
    name: build-deploy-run-db-without-data
  resources:
  - name: level3-project
    resourceRef:
      name: level3
