apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy-run
spec:
  resources:
  - name: level3-project
    type: git
  params:
  - name: IMAGE
    type: string
  - name: path
    type: string
  tasks:
  - name: build-push
    taskRef:
      name: build-push
    params:
    - name: IMAGE
      value: "$(params.IMAGE)"
    resources:
      inputs:
      - name: level3-project
        resource: level3-project
  - name: run-image
    taskRef:
      name: deploy-using-kubectl
    runAfter:
      - build-push
    params:
    - name: pathToYamlFile
      value: "$(params.path)"
    - name: image
      value: "$(params.IMAGE)"
    resources:
      inputs:
      - name: level3-project
        resource: level3-project
