apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: front-end-
spec:
  serviceAccountName: omar-docker-hub
  params:
  - name: IMAGE
    value: "ozb96/front-end"
  - name: path
    value: "templete.yaml"
  pipelineRef:
    name: build-deploy-run
  resources:
  - name: level3-project
    resourceRef:
      name: level3
