apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: level3
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/OZB96/level3-project/
