apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy-run-ingress
spec:
  resources:
  - name: level3-project
    type: git
  params:
  - name: IMAGE
    type: string
  - name: serviceName
    type: string
  - name: pathToYamlFile
    type: string
  - name: pathToServiceFile
    type: string
  - name: namespace
    type: string
  - name: CONTEXT
    type: string
  - name: DOCKERFILE
    type: string
  - name: pathToIngressFile
    type: string
  - name: namespaceProd
    type: string
  - name: pathToServiceFileTestPort
    type: string
  - name: yamlfolders
    type: string
  tasks:
  - name: build-push
    taskRef:
      name: build-push
    params:
    - name: IMAGE
      value: "$(params.IMAGE)"
    - name: CONTEXT
      value: "$(params.CONTEXT)"
    - name: DOCKERFILE
      value: "$(params.DOCKERFILE)"
    resources:
      inputs:
      - name: level3-project
        resource: level3-project
  - name: run-image
    taskRef:
      name: deploy-using-kubectl
    runAfter:
      - build-push
    params:
    - name: pathToYamlFile
      value: "$(params.pathToYamlFile)"
    - name: pathToServiceFile
      value: "$(params.pathToServiceFileTestPort)"
    - name: namespace
      value: "$(params.namespace)"
    resources:
      inputs:
      - name: level3-project
        resource: level3-project
  - name: wait-microservices
    taskRef:
      name: wait-microservices
    runAfter:
      - run-image
    params:
    - name: namespace
      value: "$(params.namespace)"
    - name: serivceName
      value: "$(params.serviceName)"
    resources:
      inputs:
      - name: level3-project
        resource: level3-project
  - name: run-test
    taskRef:
      name: run-test
    runAfter:
      - wait-microservices
    resources:
      inputs:
      - name: level3-project
        resource: level3-project
  - name: deploy-to-prod
    taskRef:
      name: deploy-using-kubectl-folder
    runAfter:
      - run-test
    params:
    - name: path
      value: "$(params.yamlfolders)"
    - name: namespace
      value: "$(params.namespaceProd)"
    resources:
      inputs:
      - name: level3-project
        resource: level3-project

