kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deploy-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "deployments.apps", "replicasets", "pods"]
  verbs: ["*"]
